### ISSUE TITLE
Road to v2.0

### ISSUE THREAD

**Issue by d4vsanchez** [ubidots/ubidots-nodered#15]
# Road to v2.0

Hey everyone, we've seen a bit of activity in this repo in the last few days, some bugs have been fixed and new features have been merged into master. This kind of activity didn't happen for some months prior. Given this reason, I think is pertinent to start thinking about our next major release for these nodes.

To create this Roadmap, we have looked up through all the feature requests that have been published on the issues section of this repository and we've also listened to our clients through support tickets and our [community forum](https://ubidots.com/community).

## Roadmap

- [ ] Upgrade MQTT library to v3.
- [ ] Keep a Changelog file to better document changes in the nodes.
- [x] Connect to the MQTT broker on deploy, not on data receival.
- [x] Give the user a way to choose which data they want to receive in the response.
- [x] Support HTTP connections to Ubidots.
- [x] Multiple listeners in single client connection.
- [x] Receive topic as an input in the payload for the out node.

**Comment by dsepulvedar** [comment]
I think is would also be great if there would be the option to establish secure connections over TLS, both for HTTP and MQTT.

**Comment by dsepulvedar** [comment]
Additional comments:

– Receive topic as an input in the payload for the out node. 
– Enable multiple variable subscription with a single in node

**Comment by d4vsanchez** [comment]
We're now in v2. There are some things that weren't added in this v2, I have edited my comment to reflect those changes.

Hope they can be added later on in v3.
